# Welcome to the configuration file for Wait2Cmd, a module included within Incore.
# Configuration is pretty easy.
general:
    # Should the module be enabled?
    enable: true
    
    # What should I tell players when they try to use a banned item?
    itemBanMessage: "&4That item can't be used."
    
    # Should I take the item from the player's inventory when they try to use it?
    removeFromInventory: true

# YOU MUST CONFIGURE THIS SECTION CORRECTLY.
# Failure to do so will result in ass gape.
# A lot of ass gape.
mysql:
    host: 127.0.0.1
    port: 3301
    database: factions
    username: root
    password: root
    table-name: 